apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.lable }}
  labels:
    app: {{.Values.lable }}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.lable }}
  template:
    metadata:
      labels:
        app: {{.Values.lable }}
    spec:
      containers:
      - name: {{.Values.lable }}
        image: {{.Values.pod.image }}
        ports:
        - containerPort: {{.Values.service.port}}
